### ISSUE TITLE
Simple but useful feature

### ISSUE THREAD

**Issue by q0r3y** [AmIJesse/LinkBait#3]
Hey! Thanks for the project. I've added a simple but useful feature on my end: 
`submitResult('url', window.location.href);`
This logs the URL that was accessed. It can be useful when you need to sift through multiple logs looking for a specific one that clicked on a custom URL.

**Comment by AmIJesse** [comment]
Ah right, I was doing something similar on the back end when the results were all submitted at once. Added it, thanks for the suggestion.
