### ISSUE TITLE
Browser: Mozilla, when using Chrome

### ISSUE THREAD

**Issue by rsewell97** [AmIJesse/LinkBait#4]
https://github.com/AmIJesse/LinkBait/blob/f051168cf5f6c8d5c08ca16a46a01b83bfc6daf8/logger.php#L194

I'm using Chrome and it is logged as Mozilla

is there a workaround for getting the correct browser?

**Comment by AmIJesse** [comment]
Interesting that I never noticed that before, according to mozilla every browser's appCodeName is "Mozilla", so I'll go ahead and remove that from the logger.
https://developer.mozilla.org/en-US/docs/Web/API/NavigatorID/appCodeName
