### ISSUE TITLE
Script relies on external scrapes for information gathering, potential information leak vector. 

### ISSUE THREAD

**Issue by gitjimmer** [AmIJesse/LinkBait#5]
logger.php makes external ajax calls for scraping purposes to the following URL's 
https://ipv6.hastysec.dev on Line 234 of logger.php
https://mtu.hastysec.dev on Line 257 of logger.php

These can be disabled in the code but should be recognised as an external call which may trigger some cross site scripting detection as well as leaking additional information about the target to the responding external service.

**Comment by AmIJesse** [comment]
Ah yeah fair point about the calls to external services. The ipv6 and mtu websites are mine which I can assure have no logging, though it wouldn't hurt to throw them up on github for others to host if they would like. 

I don't see how they could trigger XSS detection, unless there's some funky browser detection going on that I need to work around.

**Comment by Phobetor** [comment]
@AmIJesse the mtu part is actually the most interesting part here :)
Any chance you share it?

**Comment by AmIJesse** [comment]
Sorry for the long delay, I'm using https://github.com/ValdikSS/p0f-mtu on the back-end of mtu.hastysec.dev, just making the calls via go, instead of php.
