### ISSUE TITLE
Encode the php??

### ISSUE THREAD

**Issue by nikkixcool** [AmIJesse/LinkBait#6]
Let me apoligise foremost! I am still learning! Is there a way to encode or obfuscate the PHP script so someone inspecting my page can't see/easily decipher the source code itself?

I attempted using a free encoder but the script doesnt seem to work when I try using the obfuscated version. Any thoughts?

**Comment by AmIJesse** [comment]
The PHP isn't visible to the user, though the HTML/Javascript is, and the javascript is something you could obfuscate. I'll look into it and reply with another comment.

**Comment by AmIJesse** [comment]
If you copy everything under the </style> tag in the PHP file, and run it through 
http://snapbuilder.com/code_snippet_generator/obfuscate_html_source_code/
It will obfuscate it, but anyone who wanted to could reverse it relatively easily to figure out what it's actually doing.
